
spring:
  application:
    name: springboot-server-1



server:
  port: 8081
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:18090/eureka/

